[build]
  command = "pip install _submodules/insiders && mkdocs build --strict"
  publish = "site"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
		Content-Security-Policy = "frame-ancestors 'none'"
