name: Auto-comment and handle PRs and issues on label
env:
  CONTRIBUTING_LINK: https://github.com/n8n-io/n8n-docs/blob/main/CONTRIBUTING.md
on:
  issues:
    types:
      - labeled
  pull_request_target:
    types:
      - labeled
jobs:
  handle-labels:
    if: contains(fromJSON('["spam", "ai-slop", "low-effort-bad", "duplicate", "dev-cancelled", "pending-dev", "in-next-release", "old-course"]'), github.event.label.name)
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Set label config
        id: config
        run: |
          AUTHOR="${{ github.event.issue.user.login || github.event.pull_request.user.login }}"
          case "${{ github.event.label.name }}" in
            "spam")
              echo "comment=@$AUTHOR This appears to be spam. Please review n8n's [contributing](${{ env.CONTRIBUTING_LINK }}) guidelines." >> $GITHUB_OUTPUT
              echo "should_close=true" >> $GITHUB_OUTPUT
              ;;
            "ai-slop")
              echo "comment=@$AUTHOR This appears to be AI generated, and has quality or accuracy problems. Please review n8n's [contributing](${{ env.CONTRIBUTING_LINK }}) guidelines." >> $GITHUB_OUTPUT
              echo "should_close=true" >> $GITHUB_OUTPUT
              ;;
            "low-effort-bad")
              echo "comment=@$AUTHOR This is a minor contribution with quality problems. Please review n8n's [contributing](${{ env.CONTRIBUTING_LINK }}) guidelines." >> $GITHUB_OUTPUT
              echo "should_close=true" >> $GITHUB_OUTPUT
              ;;
            "duplicate")
              echo "comment=@$AUTHOR This duplicates another issue or PR, or the work was already done elsewhere. Please review n8n's [contributing](${{ env.CONTRIBUTING_LINK }}) guidelines." >> $GITHUB_OUTPUT
              echo "should_close=true" >> $GITHUB_OUTPUT
              ;;
            "old-course")
              echo "comment=Hi @$AUTHOR! Thanks for your contribution, but we are no longer updating the course. We expect to fully replace it in the coming months. Please review n8n's [contributing](${{ env.CONTRIBUTING_LINK }}) guidelines." >> $GITHUB_OUTPUT
              echo "should_close=true" >> $GITHUB_OUTPUT
              ;;
            "dev-cancelled")
              echo "comment=Hi @$AUTHOR, thanks for the pull request! \n It looks like the PR in the main repo was closed. I'm going to go ahead and close this one too since this depends on the main repo submission being accepted. Please let me know if the status changes, however, and we can re-open as needed." >> $GITHUB_OUTPUT
              echo "should_close=true" >> $GITHUB_OUTPUT
              ;;
            "pending-dev")
              echo "comment=Thanks @$AUTHOR! We'll hold off on reviewing this until the PR is ready to go in the main repo." >> $GITHUB_OUTPUT
              echo "should_close=false" >> $GITHUB_OUTPUT
              ;;
            "in-next-release")
              echo "comment=Holding off on merging until this is released." >> $GITHUB_OUTPUT
              echo "should_close=false" >> $GITHUB_OUTPUT
              ;;
          esac
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
          BODY: ${{ steps.config.outputs.comment }}
      - name: Close issue or PR
        if: steps.config.outputs.should_close == 'true'
        run: |
          if [ "${{ github.event_name }}" = "issues" ]; then
            gh issue close "$NUMBER"
          else
            gh pr close "$NUMBER"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
